AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: {{cookiecutter.description}} | {{cookiecutter.description}}
Globals:
  Function:
    Timeout: 3

Parameters:
  Environment:
    Default: {{cookiecutter.enviroment}}
    Description: Environment
    Type: String
      
Resources:
  {{cookiecutter.lambda_name}}:
    Type: AWS::Serverless::Function
    Properties:
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPython:22
      CodeUri: app/
      Handler: app.lambda_handler
      Runtime: {{cookiecutter.runtime}}
          